//! HTTP callback API — external systems write into a session's input.
//!
//! `POST http://<bind>/callback/<nick>?label=<label>` with `X-Api-Token`, and the
//! body lands in that session's terminal input as `[callback:<label>]: <text>`.
//!
//! Nothing here invents a delivery mechanism: the request is authenticated,
//! resolved to a live agent, and handed to the same `send_message` + bus publish
//! path that peer messages use, so the injection gate (no modal, no half-typed
//! operator line) and the "queue rather than drop" guarantee come for free.
//!
//! Design notes live in `docs/plans/claudebase-v0.11-callback-api.md`. The two
//! that shape this file:
//!
//! * **A token belongs to a NICK, not to an `agent_id`.** Every restart mints a
//!   new `agent_id`, so a token keyed by it would change under every script that
//!   embeds it. The nick survives restarts, and it is also what the URL carries.
//! * **The listener is off until the operator turns it on.** Tokens exist from
//!   the first registration; an open port is a separate, deliberate act.

use std::net::SocketAddr;
use anyhow::{Context, Result};
use rusqlite::{params, Connection, OptionalExtension};
use sha2::{Digest, Sha256};

use super::chat::SharedBus;

/// `daemon_state` key holding the bind address, so an enabled listener survives
/// a daemon restart without the operator re-enabling it.
const BIND_KEY: &str = "callback.bind";

/// Where the operator (and their scripts) can read a token without going
/// through an agent.
fn token_dir() -> std::path::PathBuf {
    let home = std::env::var_os("HOME")
        .or_else(|| std::env::var_os("USERPROFILE"))
        .unwrap_or_else(|| std::ffi::OsString::from("/tmp"));
    std::path::PathBuf::from(home)
        .join(".claude")
        .join("callback-tokens")
}

// ---------------------------------------------------------------------------
// storage
// ---------------------------------------------------------------------------

/// Keyed by nick alone, matching the URL: `/callback/<nick>`.
///
/// Not by (nick, cwd) — a nick identifies at most one live session, so the URL
/// could not disambiguate two rows anyway, and a lookup that can return two
/// answers for one address is a lookup that will eventually return the wrong one.
pub fn apply_migration(conn: &Connection) -> rusqlite::Result<()> {
    conn.execute_batch(
        "CREATE TABLE IF NOT EXISTS callback_tokens (
           nick       TEXT PRIMARY KEY,
           token      TEXT NOT NULL,
           label      TEXT,
           created_at INTEGER NOT NULL
         );",
    )
}

/// 32 bytes from the OS CSPRNG, hex-encoded.
///
/// Deliberately not generated by the model that hands it to the operator: LLM
/// output is not a random source, it is a biased and partly predictable one.
fn mint() -> Result<String> {
    let mut raw = [0u8; 32];
    getrandom::getrandom(&mut raw).context("callback: read CSPRNG")?;
    Ok(hex::encode(raw))
}

/// First 8 hex characters of the token's SHA-256.
///
/// Safe to print anywhere the token is not: it identifies which token is in
/// force (so a script's copy can be compared against the daemon's) without
/// being usable as one.
pub fn fingerprint(token: &str) -> String {
    let digest = Sha256::digest(token.as_bytes());
    hex::encode(digest)[..8].to_string()
}

/// The token for `nick`, creating one on first use.
///
/// Called at agent registration so a session always has a token without the
/// operator asking for it.
pub fn ensure_token(conn: &Connection, nick: &str, now_ms: i64) -> Result<String> {
    if let Some(existing) = token_for(conn, nick)? {
        return Ok(existing);
    }
    let token = mint()?;
    conn.execute(
        "INSERT OR IGNORE INTO callback_tokens (nick, token, created_at) VALUES (?1, ?2, ?3)",
        params![nick, token, now_ms],
    )
    .context("callback: store token")?;
    // A concurrent registration may have won the race; read back rather than
    // returning a token that is not the one in force.
    let stored = token_for(conn, nick)?.unwrap_or(token);
    write_token_file(nick, &stored);
    Ok(stored)
}

pub fn token_for(conn: &Connection, nick: &str) -> Result<Option<String>> {
    conn.query_row(
        "SELECT token FROM callback_tokens WHERE nick = ?1",
        params![nick],
        |row| row.get::<_, String>(0),
    )
    .optional()
    .context("callback: read token")
}

/// New token, old one dead immediately.
pub fn rotate(conn: &Connection, nick: &str, now_ms: i64) -> Result<String> {
    let token = mint()?;
    conn.execute(
        "INSERT INTO callback_tokens (nick, token, created_at) VALUES (?1, ?2, ?3) \
         ON CONFLICT(nick) DO UPDATE SET token = excluded.token, created_at = excluded.created_at",
        params![nick, token, now_ms],
    )
    .context("callback: rotate token")?;
    write_token_file(nick, &token);
    Ok(token)
}

/// Follow a rename, exactly as chat bindings do.
///
/// The token addresses the session, and the session's address just changed. A
/// token left on the abandoned nick would authenticate nobody while the scripts
/// holding it silently stopped working.
pub fn rename(conn: &Connection, old_nick: &str, new_nick: &str) -> Result<usize> {
    let moved = conn
        .execute(
            "UPDATE OR REPLACE callback_tokens SET nick = ?2 WHERE nick = ?1",
            params![old_nick, new_nick],
        )
        .context("callback: move token to new nick")?;
    if moved > 0 {
        if let Ok(Some(tok)) = token_for(conn, new_nick) {
            write_token_file(new_nick, &tok);
        }
        let _ = std::fs::remove_file(token_dir().join(old_nick));
    }
    Ok(moved)
}

/// Mirror the token into `~/.claude/callback-tokens/<nick>` (0600).
///
/// So a local script can read the secret instead of embedding it: the literal
/// then never enters the script, the shell history, or git.
fn write_token_file(nick: &str, token: &str) {
    // A nick is validated on the way into the registry, but this builds a PATH
    // — a traversal here would write outside the directory.
    if nick.is_empty() || nick.contains('/') || nick.contains('\\') || nick.contains("..") {
        tracing::warn!(nick, "refusing to write a token file for a path-unsafe nick");
        return;
    }
    let dir = token_dir();
    if let Err(e) = std::fs::create_dir_all(&dir) {
        tracing::warn!(error = %e, "callback: cannot create token dir");
        return;
    }
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let _ = std::fs::set_permissions(&dir, std::fs::Permissions::from_mode(0o700));
    }
    let path = dir.join(nick);
    if let Err(e) = std::fs::write(&path, token) {
        tracing::warn!(error = %e, "callback: cannot write token file");
        return;
    }
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let _ = std::fs::set_permissions(&path, std::fs::Permissions::from_mode(0o600));
    }
}

/// Constant-time comparison — a byte-by-byte `==` leaks the token through
/// response timing, one character at a time.
fn tokens_match(a: &str, b: &str) -> bool {
    let (a, b) = (a.as_bytes(), b.as_bytes());
    if a.len() != b.len() {
        return false;
    }
    let mut diff = 0u8;
    for (x, y) in a.iter().zip(b.iter()) {
        diff |= x ^ y;
    }
    diff == 0
}

// ---------------------------------------------------------------------------
// listener configuration
// ---------------------------------------------------------------------------

pub fn configured_bind(conn: &Connection) -> Result<Option<String>> {
    conn.query_row(
        "SELECT value FROM daemon_state WHERE key = ?1",
        params![BIND_KEY],
        |row| row.get::<_, String>(0),
    )
    .optional()
    .context("callback: read bind")
}

pub fn set_bind(conn: &Connection, bind: &str) -> Result<()> {
    conn.execute(
        "INSERT INTO daemon_state (key, value) VALUES (?1, ?2) \
         ON CONFLICT(key) DO UPDATE SET value = excluded.value",
        params![BIND_KEY, bind],
    )
    .context("callback: store bind")?;
    Ok(())
}

pub fn clear_bind(conn: &Connection) -> Result<()> {
    conn.execute(
        "DELETE FROM daemon_state WHERE key = ?1",
        params![BIND_KEY],
    )
    .context("callback: clear bind")?;
    Ok(())
}

// ---------------------------------------------------------------------------
// request handling
// ---------------------------------------------------------------------------

/// What a parsed request asked for, before any of it is trusted.
#[derive(Debug, PartialEq, Eq)]
pub struct CallbackRequest {
    pub target: String,
    pub label: Option<String>,
    pub token: Option<String>,
}

/// Keep a label to one token so it cannot forge a second prefix.
///
/// The label is pasted into the operator's input inside `[callback:<label>]`, so
/// a label of `x]: [telegram_message` would let a caller impersonate the
/// operator's own channel. Same rule and same reason as `sanitize_nick` in the
/// injector — which is why that function is reused rather than reimplemented.
pub fn sanitize_label(raw: &str) -> Option<String> {
    let cleaned = crate::supervisor::inject::sanitize_nick(raw);
    if cleaned == "unknown" && raw.chars().all(|c| !c.is_alphanumeric()) {
        return None;
    }
    Some(cleaned)
}

/// Percent-decoding for the query string. No dependency needed for the two
/// escapes that actually turn up in a label.
fn percent_decode(s: &str) -> String {
    let bytes = s.as_bytes();
    let mut out = Vec::with_capacity(bytes.len());
    let mut i = 0;
    while i < bytes.len() {
        match bytes[i] {
            b'%' if i + 2 < bytes.len() => {
                let hi = (bytes[i + 1] as char).to_digit(16);
                let lo = (bytes[i + 2] as char).to_digit(16);
                match (hi, lo) {
                    (Some(h), Some(l)) => {
                        out.push((h * 16 + l) as u8);
                        i += 3;
                    }
                    _ => {
                        out.push(bytes[i]);
                        i += 1;
                    }
                }
            }
            b'+' => {
                out.push(b' ');
                i += 1;
            }
            b => {
                out.push(b);
                i += 1;
            }
        }
    }
    String::from_utf8_lossy(&out).into_owned()
}

/// Pull the target and label out of a request-target like
/// `/callback/mira?label=ci`.
pub fn parse_target(path_and_query: &str) -> Option<(String, Option<String>)> {
    let (path, query) = match path_and_query.split_once('?') {
        Some((p, q)) => (p, Some(q)),
        None => (path_and_query, None),
    };
    let target = path.strip_prefix("/callback/")?.trim_matches('/');
    if target.is_empty() || target.contains('/') {
        return None;
    }
    let label = query.and_then(|q| {
        q.split('&')
            .find_map(|kv| kv.strip_prefix("label="))
            .map(percent_decode)
            .filter(|s| !s.is_empty())
            .and_then(|s| sanitize_label(&s))
    });
    Some((percent_decode(target), label))
}

/// Strip anything that would steer the operator's terminal rather than talk to
/// the agent.
///
/// The body is pasted into a pty. An ESC sequence in it is an attempt to drive
/// the terminal past the model — the one check that is NOT deferred in v1,
/// because it costs three lines and the body reaches the terminal directly.
pub fn sanitize_body(raw: &str) -> String {
    raw.chars()
        .filter(|c| *c == '\n' || *c == '\t' || !c.is_control())
        .collect()
}

/// The outcome of a callback, as the caller sees it.
///
/// The HTTP status is always 200 (operator decision): the caller is a debugging
/// script, not a client that needs to branch on status classes. The body still
/// says what happened, because in a debugging workflow a typo'd nick answering
/// exactly like a success is time spent chasing a delivery that never started.
#[derive(Debug)]
pub enum Outcome {
    Queued { message_id: String, target: String, subscribers: usize },
    Rejected { error: String, candidates: Vec<String> },
}

impl Outcome {
    pub fn to_json(&self) -> serde_json::Value {
        match self {
            Outcome::Queued { message_id, target, subscribers } => serde_json::json!({
                "ok": true,
                "delivery": if *subscribers > 0 { "delivered" } else { "queued" },
                "message_id": message_id,
                "target": target,
            }),
            Outcome::Rejected { error, candidates } => serde_json::json!({
                "ok": false,
                "error": error,
                "candidates": candidates,
            }),
        }
    }
}

/// Authenticate, resolve, and hand the message to the normal delivery path.
pub async fn dispatch(req: CallbackRequest, body: String, bus: &SharedBus) -> Outcome {
    let CallbackRequest { target, label, token } = req;
    let body = sanitize_body(&body);
    if body.trim().is_empty() {
        return Outcome::Rejected {
            error: "empty body".to_string(),
            candidates: vec![],
        };
    }

    let target_for_blocking = target.clone();
    let token_presented = token.unwrap_or_default();
    let resolved = tokio::task::spawn_blocking(move || -> anyhow::Result<(String, String)> {
        let conn = super::chat::open_chat_db()?;
        let agent_id = super::agent_registry::resolve_target(&conn, &target_for_blocking)?;
        // The token is checked against the NICK the URL names, so a token
        // cannot open a session other than its own.
        let nick: String = conn.query_row(
            "SELECT agent_name FROM agent_registry WHERE agent_id = ?1",
            params![agent_id],
            |row| row.get(0),
        )?;
        let expected = token_for(&conn, &nick)?
            .ok_or_else(|| anyhow::anyhow!("no callback token issued for `{nick}`"))?;
        if !tokens_match(&expected, &token_presented) {
            anyhow::bail!("unauthorized");
        }
        Ok((agent_id, nick))
    })
    .await;

    let (agent_id, nick) = match resolved {
        Ok(Ok(v)) => v,
        Ok(Err(e)) => {
            return Outcome::Rejected {
                error: e.to_string(),
                candidates: vec![],
            }
        }
        Err(e) => {
            tracing::error!(error = %e, "callback resolve panicked");
            return Outcome::Rejected {
                error: "internal error".to_string(),
                candidates: vec![],
            };
        }
    };

    deliver_resolved(&agent_id, &nick, &body, label.as_deref(), bus).await
}

/// Deliver a message that has already been authorised, to an agent named by
/// NICK, with no token involved.
///
/// This is the whole of what the UNIX-socket surface needs: a socket under the
/// user's own runtime directory is guarded by file permissions, so there is
/// nothing left for a token to prove. Sharing the code with the HTTP path is
/// the point — one delivery path means the injection gate, the storage and the
/// notification shape cannot drift apart between the two entry points.
pub async fn deliver(
    nick: &str,
    text: &str,
    label: Option<&str>,
    bus: &SharedBus,
) -> Outcome {
    let nick_owned = nick.to_string();
    let resolved = tokio::task::spawn_blocking(move || -> anyhow::Result<String> {
        let conn = super::chat::open_chat_db_readonly()?;
        super::agent_registry::resolve_target(&conn, &nick_owned)
    })
    .await;

    let agent_id = match resolved {
        Ok(Ok(id)) => id,
        Ok(Err(e)) => {
            return Outcome::Rejected {
                error: e.to_string(),
                candidates: vec![],
            }
        }
        Err(e) => {
            tracing::error!(error = %e, "socket deliver resolve panicked");
            return Outcome::Rejected {
                error: "internal error".to_string(),
                candidates: vec![],
            };
        }
    };

    deliver_resolved(&agent_id, nick, text, label, bus).await
}

async fn deliver_resolved(
    agent_id: &str,
    nick: &str,
    body: &str,
    label: Option<&str>,
    bus: &SharedBus,
) -> Outcome {
    let from = match label {
        Some(l) => format!("callback:{l}"),
        None => "callback".to_string(),
    };
    let content = body.to_string();
    let agent_for_send = agent_id.to_string();
    let from_for_send = from.clone();
    let stored = tokio::task::spawn_blocking(move || -> anyhow::Result<String> {
        let conn = super::chat::open_chat_db()?;
        let outcome = super::agent_registry::send_message(
            &conn,
            &from_for_send,
            &agent_for_send,
            &content,
            super::chat::now_millis(),
        )?;
        Ok(outcome.message_id)
    })
    .await;

    let message_id = match stored {
        Ok(Ok(id)) => id,
        Ok(Err(e)) => {
            return Outcome::Rejected {
                error: e.to_string(),
                candidates: vec![],
            }
        }
        Err(e) => {
            tracing::error!(error = %e, "callback store panicked");
            return Outcome::Rejected {
                error: "internal error".to_string(),
                candidates: vec![],
            };
        }
    };

    let thread = format!("agent:{agent_id}");
    let frame = super::chat::build_channel_notification_callback(
        body,
        label,
        agent_id,
        &message_id,
    );
    let subscribers = bus.publish(&thread, frame).await;

    tracing::info!(
        target_nick = %nick,
        label = ?label,
        %message_id,
        subscribers,
        "callback accepted"
    );

    Outcome::Queued {
        message_id,
        target: nick.to_string(),
        subscribers,
    }
}

// ---------------------------------------------------------------------------
// listener
// ---------------------------------------------------------------------------

/// Serve the callback endpoint until the process ends.
///
/// Spawned only when a bind address is configured. Bind failures are logged and
/// give up rather than taking the daemon down: a session must stay usable when
/// the extra HTTP surface cannot start.
pub async fn serve(bind: String, bus: SharedBus) {
    let addr: SocketAddr = match bind.parse() {
        Ok(a) => a,
        Err(e) => {
            tracing::error!(bind = %bind, error = %e, "callback: unparseable bind address");
            return;
        }
    };

    let listener = match tokio::net::TcpListener::bind(addr).await {
        Ok(l) => l,
        Err(e) => {
            tracing::error!(bind = %bind, error = %e, "callback: cannot bind");
            return;
        }
    };

    if !addr.ip().is_loopback() {
        tracing::warn!(
            bind = %bind,
            "callback endpoint is reachable from the network AND the token travels in cleartext \
             over plain HTTP — prefer a localhost bind plus an SSH tunnel"
        );
    }
    tracing::info!(bind = %bind, "callback endpoint listening");

    loop {
        let (stream, peer) = match listener.accept().await {
            Ok(v) => v,
            Err(e) => {
                tracing::warn!(error = %e, "callback: accept failed");
                continue;
            }
        };
        let bus = bus.clone();
        tokio::spawn(async move {
            if let Err(e) = handle_connection(stream, &bus).await {
                tracing::debug!(%peer, error = %e, "callback connection ended");
            }
        });
    }
}

/// Minimal HTTP/1.1 request handling: read headers, read the declared body,
/// answer, close.
///
/// Deliberately not a general-purpose server — it answers exactly one route and
/// closes the connection every time, so there is no keep-alive state machine to
/// get wrong.
async fn handle_connection(mut stream: tokio::net::TcpStream, bus: &SharedBus) -> Result<()> {
    use tokio::io::{AsyncReadExt, AsyncWriteExt};

    const MAX_HEAD: usize = 8 * 1024;
    const MAX_BODY: usize = 64 * 1024;

    let mut buf = Vec::with_capacity(1024);
    let mut chunk = [0u8; 1024];
    let head_end = loop {
        let n = stream.read(&mut chunk).await?;
        if n == 0 {
            anyhow::bail!("client closed before sending a request");
        }
        buf.extend_from_slice(&chunk[..n]);
        if let Some(pos) = find_head_end(&buf) {
            break pos;
        }
        if buf.len() > MAX_HEAD {
            respond(&mut stream, "413 Payload Too Large", &serde_json::json!({
                "ok": false, "error": "request head too large"
            })).await?;
            return Ok(());
        }
    };

    let head = String::from_utf8_lossy(&buf[..head_end]).to_string();
    let mut lines = head.lines();
    let request_line = lines.next().unwrap_or_default().to_string();
    let mut parts = request_line.split_whitespace();
    let method = parts.next().unwrap_or_default().to_string();
    let target = parts.next().unwrap_or_default().to_string();

    let mut token = None;
    let mut content_length = 0usize;
    for line in lines {
        let Some((name, value)) = line.split_once(':') else { continue };
        let name = name.trim().to_ascii_lowercase();
        let value = value.trim();
        match name.as_str() {
            "x-api-token" => token = Some(value.to_string()),
            "content-length" => content_length = value.parse().unwrap_or(0),
            _ => {}
        }
    }

    if !method.eq_ignore_ascii_case("POST") {
        respond(&mut stream, "405 Method Not Allowed", &serde_json::json!({
            "ok": false, "error": "use POST"
        })).await?;
        return Ok(());
    }
    if content_length > MAX_BODY {
        respond(&mut stream, "413 Payload Too Large", &serde_json::json!({
            "ok": false, "error": "body too large"
        })).await?;
        return Ok(());
    }

    let mut body = buf[head_end + 4..].to_vec();
    while body.len() < content_length {
        let n = stream.read(&mut chunk).await?;
        if n == 0 {
            break;
        }
        body.extend_from_slice(&chunk[..n]);
    }
    body.truncate(content_length);
    let body = String::from_utf8_lossy(&body).to_string();
    let body = extract_text(&body);

    let Some((route_target, label)) = parse_target(&target) else {
        respond(&mut stream, "200 OK", &serde_json::json!({
            "ok": false,
            "error": "path must be /callback/<nick>",
            "candidates": [],
        })).await?;
        return Ok(());
    };

    let outcome = dispatch(
        CallbackRequest { target: route_target, label, token },
        body,
        bus,
    )
    .await;

    // Always 200 — operator decision. The body carries the verdict.
    respond(&mut stream, "200 OK", &outcome.to_json()).await?;
    Ok(())
}

/// A JSON body of `{"text": "..."}` is unwrapped; anything else is the message.
fn extract_text(body: &str) -> String {
    let trimmed = body.trim_start();
    if trimmed.starts_with('{') {
        if let Ok(v) = serde_json::from_str::<serde_json::Value>(trimmed) {
            if let Some(t) = v.get("text").and_then(|t| t.as_str()) {
                return t.to_string();
            }
        }
    }
    body.to_string()
}

fn find_head_end(buf: &[u8]) -> Option<usize> {
    buf.windows(4).position(|w| w == b"\r\n\r\n")
}

async fn respond(
    stream: &mut tokio::net::TcpStream,
    status: &str,
    body: &serde_json::Value,
) -> Result<()> {
    use tokio::io::AsyncWriteExt;
    let payload = serde_json::to_string(body)?;
    let response = format!(
        "HTTP/1.1 {status}\r\nContent-Type: application/json\r\nContent-Length: {}\r\nConnection: close\r\n\r\n{payload}",
        payload.len()
    );
    stream.write_all(response.as_bytes()).await?;
    stream.flush().await?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn db() -> Connection {
        let c = Connection::open_in_memory().unwrap();
        apply_migration(&c).unwrap();
        c
    }

    #[test]
    fn a_token_is_minted_once_and_reused() {
        let c = db();
        let first = ensure_token(&c, "mira", 1).unwrap();
        let second = ensure_token(&c, "mira", 2).unwrap();
        assert_eq!(first, second, "a session must not get a new token per restart");
        assert_eq!(first.len(), 64, "32 bytes, hex-encoded");
    }

    #[test]
    fn rotation_invalidates_the_previous_token() {
        let c = db();
        let old = ensure_token(&c, "mira", 1).unwrap();
        let new = rotate(&c, "mira", 2).unwrap();
        assert_ne!(old, new);
        assert_eq!(token_for(&c, "mira").unwrap().unwrap(), new);
    }

    #[test]
    fn a_token_follows_a_rename() {
        // Scripts hold the token; the session's address changed, not its
        // identity. Leaving the token behind would break them silently.
        let c = db();
        let tok = ensure_token(&c, "planner", 1).unwrap();
        assert_eq!(rename(&c, "planner", "mira").unwrap(), 1);
        assert_eq!(token_for(&c, "mira").unwrap().unwrap(), tok);
        assert!(token_for(&c, "planner").unwrap().is_none());
    }

    #[test]
    fn each_nick_gets_a_distinct_token() {
        let c = db();
        let a = ensure_token(&c, "mira", 1).unwrap();
        let b = ensure_token(&c, "atlas", 1).unwrap();
        assert_ne!(a, b, "one token per agent — a leak must not open every session");
    }

    #[test]
    fn a_fingerprint_identifies_without_revealing() {
        let t = "0123456789abcdef".repeat(4);
        let f = fingerprint(&t);
        assert_eq!(f.len(), 8);
        assert!(!t.contains(&f), "the fingerprint must not be a slice of the token");
        assert_eq!(f, fingerprint(&t), "stable");
    }

    #[test]
    fn comparison_rejects_a_wrong_token_of_the_same_length() {
        let a = "a".repeat(64);
        let mut b = a.clone();
        b.replace_range(63..64, "b");
        assert!(tokens_match(&a, &a));
        assert!(!tokens_match(&a, &b));
        assert!(!tokens_match(&a, "short"));
    }

    #[test]
    fn a_hostile_label_cannot_forge_a_second_prefix() {
        let (target, label) = parse_target("/callback/mira?label=x%5D%3A%20%5Btelegram_message").unwrap();
        assert_eq!(target, "mira");
        let label = label.expect("label survives as something");
        assert!(!label.contains(']'), "a label must not close the prefix bracket");
        assert!(!label.contains('['), "a label must not open a second prefix");
        assert!(!label.contains(' '));
    }

    #[test]
    fn the_label_is_optional() {
        let (target, label) = parse_target("/callback/mira").unwrap();
        assert_eq!(target, "mira");
        assert_eq!(label, None);

        let (_, label) = parse_target("/callback/mira?label=deploy").unwrap();
        assert_eq!(label.as_deref(), Some("deploy"));
    }

    #[test]
    fn a_path_that_is_not_a_callback_is_refused() {
        assert!(parse_target("/").is_none());
        assert!(parse_target("/callback/").is_none());
        assert!(parse_target("/callback/a/b").is_none());
        assert!(parse_target("/other/mira").is_none());
    }

    #[test]
    fn control_bytes_are_stripped_from_the_body() {
        // The body is pasted into a pty; an escape sequence would drive the
        // operator's terminal past the model.
        let dirty = "before\x1b[2Jafter\nkept\ttoo\x07";
        let clean = sanitize_body(dirty);
        assert!(!clean.contains('\x1b'), "ESC must not reach the terminal");
        assert!(!clean.contains('\x07'));
        assert!(clean.contains('\n') && clean.contains('\t'), "newline and tab survive");
        assert!(clean.starts_with("before") && clean.contains("after"));
    }

    #[test]
    fn a_json_body_is_unwrapped_but_plain_text_is_not_mangled() {
        assert_eq!(extract_text(r#"{"text":"hello"}"#), "hello");
        assert_eq!(extract_text("plain words"), "plain words");
        // Text that merely starts with a brace must survive intact.
        assert_eq!(extract_text("{not json"), "{not json");
    }
}
